### ISSUE TITLE
Generate constants of table and field names ?

### ISSUE THREAD

**Issue by joeblew99** [aacanakin/qb#54]
Just an idea.

Gives string typing, so that when you refactoring your model all queries break correctly ;)

**Comment by joeblew99** [comment]
I did this on a very similar project years ago in c#.
It helped allot.


It also had a GUI took where you could see your model and control the builder a bit also.
The GUI was useful when you had a very big project I found. Was a team of 40 programmers using it.
The dB was oracle but that's beside the point.

**Comment by aacanakin** [comment]
Can you explain a bit more what you mean by generating constants of table? Maybe an example?

 Oracle can be done by just adding a new adapter to qb if there are no significant changes in the syntax. Unfortunately, I haven't used oracle. Maybe you can help with that?

**Comment by joeblew99** [comment]
I noticed the queries are using strings for table name and field name.
If you generate these as constants at design time, then it means I can use
them in the queries.

That's all. Nothing complex.

I don't want to use race. I was merely giving an example of I ast project t
where having been the contents was really useful.

Dos this make sense now ? If not just ask me again.

**Comment by cdevienne** [comment]
I am not sure I understand correctly the suggestion.

If you suggest to use constants for table names and fields, then I guess the advice apply to examples and tests, not the core library.

And if this is indeed what you suggest, then I beg to differ: The table and field objects are already providing an api to retrieve the actual names for queries, which means we actually have to write down the sql table & field names only once, when defining the schema. Afterwards, we can use the Table instance to get the actual name of a table.

This approach makes the need for a constant almost none, at least if the goal is to avoid silently breaking queries if a sql name changes.

**Comment by cdevienne** [comment]
Working on yago (https://github.com/orus-io/yago) I ended up doing exactly what was suggested: generate constants for table, column & field names... I guess I changed my mind somehow.

I suggest we close this issue, as it does not apply directly to qb anyway, unless we include the advice in the documentation.
