### ISSUE TITLE
Custom Column Type

### ISSUE THREAD

**Issue by lutfuahmet** [aacanakin/qb#57]
Is there any way to use Postgresql Custom Data type with Golang struct?

**Comment by aacanakin** [comment]
Do you mean defining postgres specific types like `UUID` or do you mean composite types in postgres like the following ?
```sql
CREATE TYPE full_address AS (
       city VARCHAR(90),
       street VARCHAR(90)
);
```
Creating composite types is currently not supported. It is also not supported in mysql as well as sqlite. There should be specific implementation to postgres which may change adapter interface.

Enforcing types is supported using type tag (if you meant postgres specific types);
```go
type User struct {
    id string `qb:"type:uuid"`
}
```

**Comment by aacanakin** [comment]
@lutfuahmet ping

**Comment by aacanakin** [comment]
This issue will be closed temporarily until ping response
