### ISSUE TITLE
Override column name in tagging?

### ISSUE THREAD

**Issue by li3p** [aacanakin/qb#58]
I have some legacy tables which shared with both new and old codes, 
Can I specify to override a column name in tagging ?

**Comment by aacanakin** [comment]
It can be done using `db` tag;
```go
type User struct {
    ID string `db:"_id"`
}
```
I'm not entirely sure that this works in every aspect of session api. You may have errors in `qb.Add(model)`. Let me know if that works.

**Comment by li3p** [comment]
using `db` tag does not help, both Add and Find cannot using the specified column name.

**Comment by aacanakin** [comment]
Ok, I'll fix this.

**Comment by proc** [comment]
Also running into this issue, just FYI

**Comment by aacanakin** [comment]
@li3p @proc The new table api design is finished. Would it be ok for you to use table api for overriding column names, or do you still want a tag that changes the sql field name of the table?

**Comment by proc** [comment]
@aacanakin that implementation looks pretty cool! Although, I think in our case, since we're dealing with a legacy database, that it might be overkill. Since the tables are not being created from scratch, we just need a way to tell qb how to map a struct field to a db column name.

**Comment by aacanakin** [comment]
Ok. Seems like I've found a solution. I'll be fixing this issue as soon as possible. It'll work like the example above.

**Comment by aacanakin** [comment]
The issue is solved. However, if you're using the builder api, you need to use the db col name.
