### ISSUE TITLE
New logger design (Custom Logger)

### ISSUE THREAD

**Issue by proc** [aacanakin/qb#60]
There doesn't seem to be a way to set a custom logger. I am using logrus, with a sink to stream logs to redis. There are options to set log flags, but not the logger itself.

**Comment by aacanakin** [comment]
You are right. Currently, there is no solution to use custom logging. There should be a logging interface that custom loggers needs to implement. I need your suggestions on logging interface. Currently, there are 3 log flags that can be converted into an interface. However, 3 logging flags would not seem to be enough. Is there a common interface that log packages implement?

**Comment by proc** [comment]
@aacanakin Check out the StdLogger interface from logrus https://github.com/Sirupsen/logrus/blob/master/logrus.go This will work with go's std log package, and should work just fine for this purpose. This is about as close to a common interface as we can get, I think.

**Comment by aacanakin** [comment]
Currently, the logging mechanism is disabled for the new expression api.This interface can be plugged in to the new expression api;
```go
type StdLogger interface {
	Print(...interface{})
	Printf(string, ...interface{})
	Println(...interface{})

	Fatal(...interface{})
	Fatalf(string, ...interface{})
	Fatalln(...interface{})

	Panic(...interface{})
	Panicf(string, ...interface{})
	Panicln(...interface{})
}
```
I want more opinions about this. I'm not sure it's the right option

**Comment by aacanakin** [comment]
Now you can't set the logger by the following code;
```go
db.Engine().SetLogger(logger)
```
The `logger` must implement the following interface;
```go
// Logger is the std logger interface of the qb engine
type Logger interface {
	Print(...interface{})
	Printf(string, ...interface{})
	Println(...interface{})

	Fatal(...interface{})
	Fatalf(string, ...interface{})
	Fatalln(...interface{})

	Panic(...interface{})
	Panicf(string, ...interface{})
	Panicln(...interface{})

	LogFlags() int
	SetLogFlags(int)
}
```
