### ISSUE TITLE
Sqlite3 error: 

### ISSUE THREAD

**Issue by lijunfeng** [aacanakin/qb#62]
session, err := qb.New("sqlite3", "./qb.db3")
	if err != nil {
		panic(err)
	}

	defer session.Close()

	fmt.Prinf("%v", session)

	// add table to metadata
	session.Metadata().Add(User{})

	// create all tables registered to metadata
	session.Metadata().CreateAll()
       --> error:not enough arguments in call to session.Metadata().CreateAll
     why?

**Comment by lijunfeng** [comment]
Has been solved, my fault.

**Comment by aacanakin** [comment]
@lijunfeng I think you're using the 0.1 release. In the 0.2 alpha the metadata has changed. There are loads of changes 0.2 alpha and it continues to change. Please wait for the 0.2 beta. It'll be freezed in beta.
