### ISSUE TITLE
Expression api test suites

### ISSUE THREAD

**Issue by aacanakin** [aacanakin/qb#75]
The files should be
- sqlite_expression_test.go
- mysql_expression_test.go
- postgres_expression_test.go

**Comment by aacanakin** [comment]
After #78, It doesn't have to include `expression` in file tests. The test suite file names would remain same.

**Comment by cdevienne** [comment]
What kind of tests would it contain ?

**Comment by aacanakin** [comment]
It is like end to end tests which contain real db connections. It will contain;
- Table creation using `qb.Table()`
- Relations using foreign keys
- CRUD operations on tables
- Table drop all
