### ISSUE TITLE
Merging dialects to single dialect.go

### ISSUE THREAD

**Issue by aacanakin** [aacanakin/qb#79]

**Comment by cdevienne** [comment]
Why do you want to do that ?
Wouldn't it make it less straightforward to implement a new dialect ?

**Comment by aacanakin** [comment]
I'm not comfortable about file size. It makes harder to find. Nothing functional will be changed. This issue still open for suggestions.

**Comment by cdevienne** [comment]
If we agree on separating dialects in their own package at some point, I suggest closing this ticket
