### ISSUE TITLE
Move dialect specific code from mapper to type

### ISSUE THREAD

**Issue by cdevienne** [aacanakin/qb#80]
Because metadata only store table definitions, it should not have to know the dialect.
Even more: a single instance of metadata should be usable on two different database connection with different dialects.

The reason why Metadata currently needs a dialect is because it uses it to initialize a Mapper.
Diving into the Mapper implementation, it uses this dialect to determinate the actual db type of unsigned int and auto_increment attributes. I think this "choice" should not be made at this level, but at the DDL generation only.

To do that, we would need two things:
- Add 'unsigned' and 'autoIncrement' attributes on TypeElem
- Add a 'dialect' argument to TypeElem.String() (and maybe rename it so we can leave a generic String() implementation for formatting purpose), so it can, if 'unsigned' or 'auto_increment' is true, do the right thing.

Thoughts ?

(I will work on a patch for this, I just wanted some feedback first)

**Comment by aacanakin** [comment]
I think you're right about the dialect dependency of metadata. unsigned & autoincrement attributes would be great for type elem. They can also be chained (you had probably thought) like in the following;
```go
id := qb.Bigint().Unsigned().AutoIncrement()
```
You'll also need to create Unsigned() & AutoIncrement() constraints in constraint.go. However, it gives access to attempt to create these constraints in unsupported dialects such as postgres. We should have panics when creating ddls if the dialect doesn't support these constraints.
