### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by cdevienne** [aacanakin/qb#98]
The README file says the license is LGPL, but the LICENSE file contains the GPL.

For my needs I would prefer the LGPL, but either way I need to know what the license is.

**Comment by cdevienne** [comment]
@aacanakin Could you settle the question ?

**Comment by aacanakin** [comment]
@cdevienne  The license should be LGPL 2.1. In readme, there's a badge. Do you mean that?

**Comment by cdevienne** [comment]
Yes thanks. I'll make a PR to update the LICENSE file.
